Repository TUK-DP/frontend, pull requests merged in 2024-03, with the labels that each got.

#34 Refactor/33
  src/component/Header.js
  src/index.css
  src/pages/Home.js
Labels: refactor

#36 [design]일기장 작성 부분 디자인 수정
  src/pages/Diary.js
  src/pages/DiaryEdit.js
  src/styles/diary.css
Labels: design

#37 Design/23 치매진단 페이지 디자인
  .env
  src/App.js
  src/assets/check.png
  src/component/Header.js
  src/index.css
  src/pages/Home.js
  src/pages/Survey.js
  src/pages/SurveyStart.js
  src/styles/SurveyStart.css
  tailwind.config.js
Labels: design

#39 Feat/30 로그인/회원가입 유효성 검증 추가/API Controller 구현
  package-lock.json
  package.json
  src/api/users.controller.js
  src/component/Header.js
  src/pages/Calendar.js
  src/pages/DiaryTest.js
  src/pages/Login.js
  src/pages/Signup.js
  src/styles/Calendar.css
  src/styles/Login.css
Labels: feat

#42 Refactor/41 전체 scroll, Header.js 수정
  src/component/Header.js
  src/index.css
Labels: refactor

#45 Refactor/43
  src/index.css
  src/pages/DiaryTest.js
Labels: refactor

#46 Refactor/44 그림일기 화살표, 일기회상 값 넘겨주기
  package-lock.json
  package.json
  src/App.js
  src/pages/DiaryTest.js
  src/pages/DiaryTestResult.js
  src/pages/Draw.js
  src/styles/SurveyStart.css
Labels: refactor

#48 Feat/47 일기 페이지 변경
  src/App.js
  src/pages/Calendar.js
  src/pages/Diary.js
  src/pages/DiaryEdit.js
  src/pages/DiaryImageShow.js
  src/pages/DiaryShow.js
Labels: feat

#50 Refactor/49 일기회상, 일기작성 수정
  src/pages/DiaryShow.js
  src/styles/diary.css
Labels: refactor

#52 Design/40 일기회상 결과 페이지 디자인
  src/pages/DiaryTestResult.js
Labels: design

#53 Feat/51 일기 작성,수정,조회 API 연결
  .env
  src/App.js
  src/api/diary.controller.js
  src/pages/Calendar.js
  src/pages/Diary.js
  src/pages/DiaryShow.js
  src/pages/DiaryWrite.js
Labels: feat

#55 [feat] 일기회상 api 연동
  src/api/diary.controller.js
  src/pages/DiaryTest.js
Labels: feat

#57 Refactor/56 일기 API 수정
  src/api/common.controller.js
  src/api/diary.controller.js
  src/pages/Calendar.js
  src/pages/Diary.js
  src/pages/DiaryWrite.js
Labels: refactor

#60 [feat]DiaryShow에서 일기회상으로 diaryId 전달
  src/api/diary.controller.js
  src/pages/DiaryShow.js
  src/pages/DiaryTest.js
Labels: feat

#62 Refactor/59 일기회상 문제 생성할 수 없는 경우 처리
  src/App.js
  src/api/diary.controller.js
  src/pages/DiaryShow.js
  src/pages/DiaryTest.js
  src/pages/Error.js
Labels: refactor

#64 Refactor/61
  src/pages/Diary.js
  src/pages/DiaryWrite.js
Labels: refactor

#66 feat/63 일기회상 결과보러가기, 홈으로가기 구현
  src/pages/DiaryTest.js
  src/pages/DiaryTestResult.js
  src/pages/DiaryTestSubmit.js
Labels: feat

#68 feat/67 미래 일기 작성 막아두기
  src/pages/Calendar.js
Labels: feat

#72 Refactor/71
  src/pages/Diary.js
  src/pages/DiaryShow.js
Labels: refactor

#76 [refactor]일기 표시 수정
  src/pages/Diary.js
Labels: refactor

#77 Refactor/74 에러페이지, DiaryShow 페이지
  src/pages/DiaryShow.js
  src/pages/Error.js
Labels: refactor

#80 Refactor/78 수정
  src/pages/Calendar.js
  src/pages/DiaryTestSubmit.js
  src/pages/DiaryWrite.js
  src/pages/Home.js
  src/pages/gamePages/game2.js
  src/pages/gamePages/game3.js
  src/pages/gamePages/game5.js
Labels: refactor

#81 [refactor] 치매진단 url 수정
  src/api/survey.controller.js
  src/api/test.controller.js
Labels: refactor

#84 Refactor/83 홈화면 tailwind css 적용
  src/App.js
  src/component/Header.js
  src/component/Navbar.js
  src/index.css
  src/pages/Home.js
Labels: refactor

#85 Refactor/82 일기회상 제출 페이지 수정
  src/component/QuizBox.js
  src/pages/Calendar.js
  src/pages/Diary.js
  src/pages/DiaryShow.js
  src/pages/DiaryTest.js
  src/pages/DiaryTestResult.js
  src/redux/config/configStore.js
  src/redux/modules/DiaryInfo.js
  src/styles/QuizBox.css
Labels: refactor

#87 Refactor/86 Header, Navbar 반응형으로 수정
  src/component/Header.js
  src/component/Navbar.js
Labels: refactor

#89 [refactor]전체 틀 수정
  src/App.js
  src/component/Header.js
  src/component/Navbar.js
  src/index.css
Labels: refactor

#92 [refactor] 페이지 이동 시 스크롤 시작 위치 수정
  src/App.js
Labels: refactor

#93 [fix]일기 내용 작성하지 않으면 알림 띄움
  src/pages/Diary.js
  src/pages/DiaryWrite.js
Labels: fix

#96 [refactor]scroll 수정
  src/App.js
  src/index.css
Labels: refactor

#101 [chore] 자동화 배포 스크립트 수정
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  public/index.html
Labels: chore

#105 Feat/98 로딩창 구현
  src/assets/Rolling-1.4s-254px.gif
  src/component/Loading.js
  src/pages/Diary.js
  src/pages/DiaryWrite.js
  src/styles/diary.css
Labels: feat

#108 Refactor/107 데모 전 수정
  src/component/Loading.js
  src/index.css
  src/pages/Calendar.js
  src/pages/Draw.js
Labels: refactor

#110 Refactor/109 마진, 스크롤 수정
  src/App.js
  src/pages/DiaryTestResult.js
Labels: refactor

#111 [refactor]일기 선택 시, 렌더링 문제 해결
  src/pages/Calendar.js
Labels: refactor

#125 Refactor/115
  src/component/Button.js
  src/font/esamanru_Light.ttf
  src/index.css
  src/pages/DiaryWrite.js
Labels: refactor

#127 [fix]캘린더 날짜 오류 해결
  src/pages/Calendar.js
Labels: fix

#132 [chore]react-icons 설치
  package-lock.json
  package.json
Labels: chore
