Repository TUK-DP/frontend, pull requests merged in 2024-06, with the labels that each got.

#215 Design/214 그림일기 ui 수정
  package-lock.json
  package.json
  src/App.js
  src/api/img.controller.js
  src/component/BackGroundSkyButton.js
  src/component/ImageDiary/AIModal.js
  src/component/ImageDiary/Color.js
  src/component/ImageDiary/Palette.js
  src/pages/Calendar/Draw.js
  src/pages/ImageDiary/HelpForAi.js
  src/pages/ImageDiary/ShowAiResult.js
  src/pages/Login.js
  src/pages/Signup.js
  src/styles/Login.css
Labels: design

#217 Feat/156 마이페이지
  src/App.js
  src/api/common.controller.js
  src/api/diary.controller.js
  src/api/users.controller.js
  src/component/MyPageList.js
  src/hooks/useLogin.js
  src/index.js
  src/pages/Calendar/Calendar.js
  src/pages/Calendar/Diary.js
  src/pages/Calendar/DiaryShow.js
  src/pages/DiaryManagement.js
  src/pages/Home.js
  src/pages/MyPage.js
  src/pages/Survey/SurveyStart.js
  src/pages/UserUpdate.js
  src/redux/config/configStore.js
  src/redux/modules/DiaryDate.js
  src/redux/modules/UserInfo.js
  src/redux/modules/fontSize.js
  src/styles/SurveyStart.css
  src/styles/diary.css
Labels: feat

#222 [feat] api 키 마이페이지에서 입력 받을수 있게 구현
  src/App.js
  src/component/MyPageItem.js
  src/pages/ImageDiary/HelpForAi.js
  src/pages/MyPages/APIKeyInput.js
  src/pages/MyPages/DiaryManagement.js
  src/pages/MyPages/MyPage.js
  src/pages/MyPages/UserUpdate.js
  src/recoil/apiKeyStore.js
Labels: feat

#228 Refactor/218
  package-lock.json
  package.json
  src/App.js
  src/api/diary.controller.js
  src/component/ImageDiary/AIModal.js
  src/component/ImageDiary/Canvas.js
  src/component/ImageDiary/Color.js
  src/component/ImageDiary/DrawTools.js
  src/component/ImageDiary/Palette.js
  src/component/ImageDiary/useDrawInputEvents.js
  src/component/MyPageItem.js
  src/index.js
  src/pages/Calendar/Calendar.js
  src/pages/Calendar/Diary.js
  src/pages/Calendar/DiaryShow.js
  src/pages/Calendar/Draw.js
  src/pages/DiaryManagement.js
  src/pages/ImageDiary/HelpForAi.js
  src/pages/ImageDiary/ShowAiResult.js
  src/pages/MyPages/APIKeyInput.js
  src/pages/MyPages/DiaryManagement.js
  src/pages/MyPages/MyPage.js
  src/pages/MyPages/UserUpdate.js
  src/pages/UserUpdate.js
  src/recoil/apiKeyStore.js
  src/recoil/canvasState.js
  src/recoil/keywordState.js
  src/redux/config/configStore.js
  src/redux/modules/DiaryInfo.js
  src/redux/modules/ImageDiary.js
Labels: refactor

#229 [refactor] 키워드별 사진 업로드, 변환 예외처리
  src/pages/Calendar/Draw.js
Labels: refactor

#230 Fix/223 AI 사진 생성 후, 생기는 오류 해결
  src/component/ImageDiary/Canvas.js
  src/component/ImageDiary/DrawTools.js
  src/component/ImageDiary/useDrawInputEvents.js
  src/pages/Calendar/Diary.js
  src/pages/Calendar/DiaryShow.js
  src/pages/Calendar/Draw.js
  src/pages/ImageDiary/HelpForAi.js
  src/recoil/canvasDrawingState.js
  src/styles/diary.css
Labels: fix

#231 Fix/226 일기 내용 입력 시 스크롤 올라가는 현상 수정
  package-lock.json
  package.json
  src/pages/Calendar/Diary.js
Labels: fix
