Repository TUK-DP/frontend, pull requests merged in 2024-05, with the labels that each got.

#177 Feat/171 스켈레톤 UI
  src/component/SkeletonSurvey.js
  src/pages/Survey.js
  src/styles/Skeleton.css
Labels: feat

#182 Refactor/178 api url 변경
  src/api/diary.controller.js
  src/pages/Calendar.js
  src/pages/Diary.js
  src/pages/DiaryShow.js
  src/pages/Draw.js
  src/pages/Login.js
Labels: refactor

#185 Feat/173 그림일기 수정 중
  public/Background/blossom.png
  public/Background/cloud.png
  public/Background/day.png
  public/Background/leave.png
  public/Background/night.png
  public/Background/rain.png
  public/Background/snow.png
  public/Background/wind.png
  src/api/diary.controller.js
  src/api/img.controller.js
  src/api/keyword.controller.js
  src/pages/Diary.js
  src/pages/DiaryShow.js
  src/pages/Draw.js
  src/pages/Draw2.js
  src/pages/PhotoEdit.js
Labels: feat

#190 [refactor] 치매센터 검색창, 제출답안 수정
  src/component/QuizBox.js
  src/pages/DementiaCenter.js
Labels: refactor

#193 [fix] 카카오 맵 오류 해결 및 주변 치매 센터 가져오기 코드 리팩토링
  .prettierrc
  package-lock.json
  package.json
  src/component/DementiaList.js
  src/hooks/useGetNearByCenter.js
  src/pages/CenterMap.js
  src/pages/DementiaCenter.js
  tailwind.config.js
Labels: chore, fix, refactor

#194 Feat/161 키워드 그래프 시각화
  src/api/diary.controller.js
  src/component/Graphs.js
  src/layout/MainLayout.js
  src/pages/DiaryTest.js
  src/pages/DiaryTestResult.js
  src/pages/DiaryTestSubmit.js
  src/pages/Explain.js
  src/pages/Keyword.js
Labels: feat

#197 Refactor/195 페이지 이름 수정
  src/App.js
  src/pages/DementiaCenter.js
  src/pages/Explain.js
  src/pages/Keyword.js
Labels: refactor

#201 Feat/173 그림일기 수정
  package-lock.json
  package.json
  src/component/ImageDiary/Image.js
  src/component/ImageDiary/Image2.js
  src/component/ImageDiary/InfiniteScroll.js
  src/pages/Draw.js
  src/pages/PhotoEdit.js
  src/styles/Moveable.css
Labels: feat

#200 [refactor] 치매진단 스켈레톤 UI 수정
  src/component/SkeletonSurvey.js
  src/pages/Survey.js
  src/styles/Skeleton.css
Labels: refactor

#204 [refactor] 키워드 그래프 간격, 노드 가중치, 관계값 수정
  src/component/Graphs.js
Labels: refactor

#207 [refactor] 그림 편집 시, 빈 곳 선택하면 취소
  src/pages/PhotoEdit.js
  src/pages/gamePages/BeforeGame.js
Labels: refactor

#213 [refator] 디렉토리 구조 변경
  src/App.js
  src/component/Center/DementiaList.js
  src/component/Center/KakaoMap.js
  src/component/Dementia/ChartGraph.js
  src/component/Dementia/CompareChart.js
  src/component/Dementia/SkeletonSurvey.js
  src/component/Graphs.js
  src/component/Quiz/QuizBox.js
  src/component/QuizBox.js
  src/pages/Calendar/Calendar.js
  src/pages/Calendar/Diary.js
  src/pages/Calendar/DiaryImageShow.js
  src/pages/Calendar/DiaryShow.js
  src/pages/Calendar/DiaryWrite.js
  src/pages/Calendar/Draw.js
  src/pages/Calendar/PhotoEdit.js
  src/pages/CenterPages/CenterMap.js
  src/pages/CenterPages/DementiaCenter.js
  src/pages/Explain.js
  src/pages/Gym/Gymnastics.js
  src/pages/Gym/GymnasticsVideo.js
  src/pages/Keyword/Explain.js
  src/pages/Keyword/Keyword.js
  src/pages/Survey/PrevSurveyResult.js
  src/pages/Survey/Survey.js
  src/pages/Survey/SurveyError.js
  src/pages/Survey/SurveyResult.js
  src/pages/Survey/SurveyStart.js
  src/pages/Test/DiaryTest.js
  src/pages/Test/DiaryTestResult.js
  src/pages/Test/DiaryTestSubmit.js
  src/pages/Test/Error.js
  src/pages/gamePages/Games.js
Labels: refactor
