Repository TUK-DP/frontend, pull requests merged in 2024-02, with the labels that each got.

#3 Chore/2 - Redux 기본 설정
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/index.js
  src/logo.svg
  src/redux/config/configStore.js
  src/redux/modules/ex.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: chore

#9 Refactor/8
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/component/Header.js
  src/component/ImageDiary/Canvas.js
  src/component/ImageDiary/Image.js
  src/component/Navbar.js
  src/index.css
  src/pages/DiaryShow.js
  src/pages/Draw.js
  src/pages/PhotoEdit.js
  src/redux/config/configStore.js
  src/redux/modules/uriSave.js
  src/redux/modules/urlSave.js
Labels: refactor

#12 Design/10
  src/App.js
  src/component/Header.js
  src/index.css
  src/pages/DiaryTest.js
  src/pages/Games.js
  src/pages/gamePages/game1.js
  src/pages/gamePages/game2.js
  src/pages/gamePages/game3.js
  src/pages/gamePages/game4.js
  src/pages/gamePages/game5.js
Labels: design

#14 Feat/13
  src/App.js
  src/component/QuizBox.js
  src/index.css
  src/pages/DiaryTest.js
  src/pages/DiaryTestSubmit.js
  src/pages/Home.js
  src/styles/QuizBox.css
Labels: feat

#16 Feat/15
  src/component/Header.js
  src/component/ImageDiary/Canvas.js
  src/pages/Draw.js
Labels: feat

#17 Design/11
  src/App.js
  src/component/Navbar.js
  src/pages/Calendar.js
  src/pages/Diary.js
  src/pages/DiaryEdit.js
  src/pages/Home.js
  src/styles/Calendar.css
  src/styles/DiaryEdit.css
  src/styles/diary.css
Labels: design, feat

#19 [chore] axios 를 위한 controller 구현
  .env
  src/api/common.controller.js
  src/api/diary.controller.js
  src/api/survey.controller.js
  src/axiosTest.js
Labels: chore

#21 [feat] 설문 페이지 틀 구현
  .env
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/api/common.controller.js
  src/api/survey.controller.js
  src/index.css
  src/pages/Home.js
  src/pages/Survey.js
  src/tailwind.config.js
Labels: feat

#25 [chore] tailwindcss Setting
  package-lock.json
  package.json
  src/index.css
  src/pages/Survey.js
  tailwind.config.js
Labels: chore

#27 [feat] Draggable 경계 추가
  .gitignore
  src/component/ImageDiary/Image.js
Labels: feat

#28 Feat/22 일기 작성 기능 구현
  src/pages/Calendar.js
  src/pages/DiaryEdit.js
  src/redux/config/configStore.js
  src/redux/modules/DiaryDate.js
  src/styles/Calendar.css
  src/styles/DiaryEdit.css
  src/styles/diary.css
Labels: feat

#29 Feat/6 회원 관련 퍼블리싱
  .env
  package-lock.json
  package.json
  src/App.js
  src/assets/diary.png
  src/assets/user.png
  src/component/MyPageList.js
  src/pages/MyPage.js
Labels: design

#32 [design]주변치매센터 페이지 퍼블리싱
  src/App.js
  src/assets/search.png
  src/component/DementiaList.js
  src/pages/DementiaCenter.js
Labels: design
